spring:
  application:
    name: social_network
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/social_network}
    username: ${JDBC_USERNAME:pguser}
    password: ${JDBC_PASSWORD:pgpwd}

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: ${SPRING_JDBC:ERROR}
    org.springframework.security: ${SPRING_SECURITY:ERROR}

jwt:
  expiration_minutes: ${JWT_EXPIRATION_MINUTES:60}
  private_key:
    path: ${JWT_PRIVATE_KEY_PATH:classpath:jwt/private_key.der}
    alg: "RSA"

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      application: social_network
  prometheus:
    metrics:
      export:
        enabled: true
