spring:
  application:
    name: social_network
  datasource:
    master:
      name: master
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${JDBC_MASTER_URL:jdbc:postgresql://localhost:5432/social_network}
      username: ${JDBC_USERNAME:pguser}
      password: ${JDBC_PASSWORD:pgpwd}
    slave:
      name: replic
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${JDBC_SLAVE_URL:jdbc:postgresql://localhost:5432/social_network}
      username: ${JDBC_USERNAME:pguser}
      password: ${JDBC_PASSWORD:pgpwd}
  liquibase:
    url: ${spring.datasource.master.jdbc-url}
    user: ${spring.datasource.master.username}
    password: ${spring.datasource.master.password}

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: ${SPRING_JDBC:ERROR}
    org.springframework.security: ${SPRING_SECURITY:ERROR}

jwt:
  expiration_minutes: ${JWT_EXPIRATION_MINUTES:60}
  alg: "RSA"
  private_key:
    path: ${JWT_PRIVATE_KEY_PATH:classpath:jwt/private_key.der}
  public_key:
    path: ${JWT_PUBLIC_KEY_PATH:classpath:jwt/public_key.der}


management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
        "[spring.data.repository.invocations]": true
    tags:
      application: social_network
  prometheus:
    metrics:
      export:
        enabled: true

otel:
  propagators:
    - tracecontext
  resource:
    attributes:
      deployment.environment: dev
      service:
        name: social_network
        namespace: otus_highload
  instrumentation:
    micrometer:
      enabled: true
